name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configura o Node.js e habilita o cache para pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' 
      
      # A maneira correta de instalar e usar pnpm no GitHub Actions
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # ou a versão que você usa

      # Usa pnpm para instalar as dependências
      - name: Install Dependencies
        run: pnpm install

      # Usa pnpm para construir o projeto, com a variável de ambiente correta
      - name: Build
        env:
          NEXT_PUBLIC_BASE_PATH: /futuro-corp-website
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4